### ISSUE TITLE
Aktywności - design listy aktywności

### ISSUE THREAD

**Issue by pkasperczyk** [Krakow2016/wolontariusze#17]
Design listy aktywności, który umożliwiałby:
- wyszukiwanie
- sortowanie (np. pod względem czasu)
- dodawanie
- usuwanie
- edycję aktywności

Te funkcjonalności mogą być podzadaniami

I widzę to tak:
mogłaby być lista, gdzie byłyby wszystkie aktywności lub wszystkie dla danej sekcji, grupy, itp.
ale mogła być też lista, gdzie byłyby wszystkie aktywności, które stworzył dany koordynator

**Comment by pkasperczyk** [comment]
Teraz chciałbym się zająć tym zadaniem. Widziałem że wprowadzona została obsługa do bazy rethinkDB dla wolontariuszy i komentarzy do nich. Czy rozwijać od razu obsługę aktywności o tą bazę?

**Comment by Stanley** [comment]
Jeżeli nie będzie to dla Ciebie problemem to tak ;) W razie czego możesz to zrobić tylko na statycznych plikach.

**Comment by pkasperczyk** [comment]
Mam problem podczas wykonywania akcji update. Podobny problem pojawia mi się dla komentarzy do profili (operacje na plikach, nie na bazie) dlatego tu zamieszczam logi z konsoli przeglądarki, w momencie kiedy edytuję komentarz i naciskam "zapisz".

```
"Fluxible " "Fluxible instance instantiated" " +0ms" Object { component: function (), stores: Array[8] } client.js:2409
"Example " "rehydrating app" " +3ms" client.js:2409
"Fluxible " "rehydrate" " +1ms" Object { context: Object, plugins: Object } client.js:2409
"Routr:router " "new Router, routes = " " +91ms" Object { home: Object, registration: Object, volonteer: Object, activity: Object, login: Object, settings: Object, search: Object } client.js:2409
"Example " "React Rendering" " +7ms" client.js:2409
"Warning: Unsupported style property text-align. Did you mean textAlign?" client.js:61997
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of VolonteerList. See https://fb.me/react-warning-keys for more information." client.js:61997
"Example " "React Rendered" " +62ms" client.js:2409
"NavLink " "dispatchNavAction: action=NAVIGATE" " +1s" "/wolontariusz/2" undefined undefined client.js:2409
"Fluxible:Context " "Executing action  with payload" " +1ms" Object { type: "click", url: "/wolontariusz/2", preserveScrollPosition: undefined, params: undefined } client.js:2409
"navigateAction " "dispatching NAVIGATE_START" " +19ms" Object { type: "click", url: "/wolontariusz/2", preserveScrollPosition: undefined, params: undefined } client.js:2409
"Dispatchr:DispatcherContext " "dispatching NAVIGATE_START" " +0ms" Object { type: "click", url: "/wolontariusz/2", preserveScrollPosition: undefined, params: undefined } client.js:2409
"Dispatchr:Action " "executing handler for RouteStore" " +1ms" client.js:2409
"Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (muiTheme) while mounting Tab (see: http://fb.me/react-context-by-parent)" client.js:61997
"RoutingContainer " "component did update" " +122ms" null Object { isActive: function (), makePath: function (), context: Object, currentNavigate: Object, currentNavigateError: null, isNavigateComplete: false, currentRoute: Object } client.js:2409
"RoutingContainer " "on click navigation, reset scroll position to (0, 0)" " +10ms" client.js:2409
"Dispatchr:DispatcherContext " "finished NAVIGATE_START" " +6ms" client.js:2409
"navigateAction " "executing" " +0ms" Object { type: "click", url: "/wolontariusz/2", preserveScrollPosition: undefined, params: undefined } client.js:2409
"navigateAction " "executing route action" " +1ms" client.js:2409
"Fluxible:Context " "Executing action  with payload" " +0ms" Object { size: 8, _root: Object, __ownerID: undefined, __hash: undefined, __altered: false } client.js:2409
GET http://localhost:7000/undefined [HTTP/1.1 500 Internal Server Error 23ms]
"Dispatchr:DispatcherContext " "dispatching UPDATE_PAGE_TITLE" " +67ms" Object { pageTitle: "2 [Dynamic Page] | flux-examples | routing" } client.js:2409
"Dispatchr:Action " "executing handler for ApplicationStore" " +0ms" client.js:2409
"Dispatchr:DispatcherContext " "finished UPDATE_PAGE_TITLE" " +1ms" client.js:2409
"Fluxible:Context " "Executing action  with payload" " +0ms" Object { id: "2" } client.js:2409
"Fluxible:FetchrPlugin " "service proxy" " +32ms" client.js:2409
"Fluxible:FetchrPlugin " "service proxy callback" " +392ms" Object { id: "2", is_admin: true, first_name: "Karol", last_name: "Wojtyła", email: "karol@wojtyla.pl", password: "karol", city: "Wadowice", profile_picture: "http://i.picresize.com/images/2015/05/25/Fj0AB.jpg", background_picture: "http://www.fakt.pl/m/crop/-658/-500/faktonline/635660778242473315.jpg", interests: "piłka nożna i sporty zespołowe. Uwielbiam wycieczki po górach i jajecznicę w schronisku po całym dniu wspinaczki.", 3 więcej… } undefined client.js:2409
"Dispatchr:DispatcherContext " "dispatching LOAD_VOLONTEER" " +0ms" Object { id: "2", is_admin: true, first_name: "Karol", last_name: "Wojtyła", email: "karol@wojtyla.pl", password: "karol", city: "Wadowice", profile_picture: "http://i.picresize.com/images/2015/05/25/Fj0AB.jpg", background_picture: "http://www.fakt.pl/m/crop/-658/-500/faktonline/635660778242473315.jpg", interests: "piłka nożna i sporty zespołowe. Uwielbiam wycieczki po górach i jajecznicę w schronisku po całym dniu wspinaczki.", 3 więcej… } client.js:2409
"Dispatchr:Action " "executing handler for Volonteers" " +0ms" client.js:2409
"Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (muiTheme) while mounting Tab (see: http://fb.me/react-context-by-parent)" client.js:61997
"Dispatchr:Action " "executing handler for NewComment" " +33ms" client.js:2409
"Dispatchr:DispatcherContext " "finished LOAD_VOLONTEER" " +4ms" client.js:2409
"Dispatchr:DispatcherContext " "dispatching NAVIGATE_SUCCESS" " +71ms" Object { size: 8, _root: Object, __ownerID: undefined, __hash: undefined, __altered: false } client.js:2409
"Dispatchr:Action " "executing handler for RouteStore" " +0ms" client.js:2409
"Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (muiTheme) while mounting Tab (see: http://fb.me/react-context-by-parent)" client.js:61997
"RoutingContainer " "component did update" " +41ms" null Object { isActive: function (), makePath: function (), context: Object, currentNavigate: Object, currentNavigateError: null, isNavigateComplete: true, currentRoute: Object } client.js:2409
"Dispatchr:DispatcherContext " "finished NAVIGATE_SUCCESS" " +2ms" client.js:2409
"show comments" client.js:1518
"Fluxible:Context " "Executing action  with payload" " +2s" Object { volonteerId: "2" } client.js:2409
"Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (muiTheme) while mounting Tab (see: http://fb.me/react-context-by-parent)" client.js:61997
"profile comment read" client.js:102
"Fluxible:FetchrPlugin " "service proxy" " +46ms" client.js:2409
"Fluxible:FetchrPlugin " "service proxy callback" " +48ms" Array [ Object, Object, Object ] undefined client.js:2409
"Dispatchr:DispatcherContext " "dispatching LOAD_COMMENTS" " +0ms" Array [ Object, Object, Object ] client.js:2409
"Dispatchr:Action " "executing handler for Comments" " +0ms" client.js:2409
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of ProfileComments. See https://fb.me/react-warning-keys for more information." client.js:61997
"Dispatchr:DispatcherContext " "finished LOAD_COMMENTS" " +45ms" client.js:2409
"RoutingContainer " "remember scroll position" " +953ms" Object { x: 0, y: 117 } client.js:2409
"Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See ProfileComment" client.js:61997
"Warning: Use the `defaultValue` or `value` props instead of setting children on <textarea>." client.js:61997
"RoutingContainer " "remember scroll position" " +21s" Object { x: 0, y: 289 } client.js:2409
POST http://localhost:7000/api [HTTP/1.1 500 Internal Server Error 7ms]
"Fluxible:Context " "Executing action  with payload" " +4s" Object { volonteerId: 2, id: 1, adminId: 1, text: "To jest pierwszy komentarz (W2)a", creationTimestamp: 2200043, first_name: "Faustyna" } client.js:2409
"profile comment update" client.js:119
"Fluxible:FetchrPlugin " "service proxy" " +4ms" client.js:2409
"FetchrClient " "Syncing Comments failed: statusCode=500" " +16ms" "info" "FetcherClient" client.js:2409
"Fluxible:FetchrPlugin " "service proxy callback" " +0ms" undefined undefined client.js:2409
Error: TypeError: Cannot read property &#39;requests&#39; of undefined<br> &nbsp; &nbsp;at /home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/fluxible-plugin-fetchr/node_modules/fetchr/libs/fetcher.js:118:40<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/express/lib/router/layer.js:82:5)<br> &nbsp; &nbsp;at trim_prefix (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/express/lib/router/index.js:302:13)<br> &nbsp; &nbsp;at /home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/express/lib/router/index.js:270:7<br> &nbsp; &nbsp;at Function.proto.process_params (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/express/lib/router/index.js:321:12)<br> &nbsp; &nbsp;at next (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/express/lib/router/index.js:261:10)<br> &nbsp; &nbsp;at SessionStrategy.strategy.pass (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/passport/lib/middleware/authenticate.js:318:9)<br> &nbsp; &nbsp;at /home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/passport/lib/strategies/session.js:61:12<br> &nbsp; &nbsp;at pass (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/passport/lib/authenticator.js:333:31)<br> &nbsp; &nbsp;at deserialized (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/passport/lib/authenticator.js:345:7)

Ślad stosu:
io/<@http://localhost:7000/js/client.js:4322:13
once/<@http://localhost:7000/js/client.js:19341:5
loadFunc@http://localhost:7000/js/client.js:19218:9
readystatechange@http://localhost:7000/js/client.js:19154:13
```

**Comment by pkasperczyk** [comment]
Zaczęło działać jak w server.js dodałem zmiany obecne tutaj: 
https://github.com/yahoo/fluxible-plugin-fetchr/commit/7aec7c659e9d2fe0d2aeb6159690d5425bb73cc4

```
  // Set up the fetchr middleware
  server.use(jsonParser);
  server.use(fetchrPlugin.getXhrPath(), fetchrPlugin.getMiddleware());
```

**Comment by Stanley** [comment]
Dzięki za zwrócenie uwagi! Faktycznie był błąd spowodowany tym, że musiałem wyłączyć `jsonParser` dla ścieżki `/search`. Teraz powinno już być dobrze :)

**Comment by pkasperczyk** [comment]
Update:
Potrzebna jest strona, gdzie będą pokazane zadania utworzone przez koordynatorów, do których potrzeba, aby zgłosili się wolontariusze. Jeżeli zadanie zostanie już obsadzone, to powinno znikać z takiej strony. A jeżeli ktoś wypisał się z zadania, to zadanie wraca ponownie na tą stronę.

Może na tej stronie potrzebny jest podział zadań na kategorie albo lokalizację
