### ISSUE TITLE
problem z uruchomieniem "gulp"

### ISSUE THREAD

**Issue by pkasperczyk** [Krakow2016/wolontariusze#5]
Ściągnąłem repozytorium, node.js
Uruchamiam komendę:
npm install 
lub 
npm install -g
zależnośći się ściągają, ale dostaję takie coś jak chcę uruchomić "gulp"
"gulp: nie znaleziono polecenia"

Zacząłęm pracować na debianie.

EDIT: z tym sobie poradziłem, korzystając z tej strony :http://stackoverflow.com/questions/14657170/installing-global-npm-dependencies-via-package-json

Mam teraz inny problem:
podczas uruchomienia polecenia gulp dostaję:

```
[14:39:06] Using gulpfile /home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/Gulpfile.js
[14:39:06] Starting 'app'...
[14:39:06] Starting 'vendor'...
/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/gulp/node_modules/vinyl-fs/node_modules/vinyl/index.js:143
      throw new Error('File.contents can only be a Buffer, a Stream, or null.'
            ^
Error: File.contents can only be a Buffer, a Stream, or null.
    at File.Object.defineProperty.set (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/gulp/node_modules/vinyl-fs/node_modules/vinyl/index.js:143:13)
    at Readable.<anonymous> (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/gulp/vendor.js:31:21)
    at Readable.emit (events.js:107:17)
    at Labeled.<anonymous> (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/browserify/node_modules/read-only-stream/index.js:27:44)
    at Labeled.emit (events.js:107:17)
    at Labeled.<anonymous> (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/i
    at Labeled.emit (events.js:129:20)
    at Deps.<anonymous> (/home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/inde
    at Deps.emit (events.js:107:17)
    at /home/pkasperczyk/Pulpit/Sprawy/sprawa1_sdm/wolontariusze/node_modules/browserify/node_modules/module-deps/index.js:344:30
```

**Comment by Stanley** [comment]
Dzięki za zgłoszenie, faktycznie był błąd. Poprawiłem go w https://github.com/Krakow2016/wolontariusze/commit/841905e15f15fdf186f9ce5f1b2113a17d93a06b.
